#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSV")]
	public partial class QLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangViPham(BangViPham instance);
    partial void UpdateBangViPham(BangViPham instance);
    partial void DeleteBangViPham(BangViPham instance);
    partial void InsertbangDiem(bangDiem instance);
    partial void UpdatebangDiem(bangDiem instance);
    partial void DeletebangDiem(bangDiem instance);
    partial void InsertdiemDanh(diemDanh instance);
    partial void UpdatediemDanh(diemDanh instance);
    partial void DeletediemDanh(diemDanh instance);
    partial void InsertGiaoVien(GiaoVien instance);
    partial void UpdateGiaoVien(GiaoVien instance);
    partial void DeleteGiaoVien(GiaoVien instance);
    partial void InserthocPhan(hocPhan instance);
    partial void UpdatehocPhan(hocPhan instance);
    partial void DeletehocPhan(hocPhan instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertLOAITAIKHOAN(LOAITAIKHOAN instance);
    partial void UpdateLOAITAIKHOAN(LOAITAIKHOAN instance);
    partial void DeleteLOAITAIKHOAN(LOAITAIKHOAN instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void Insertkhoa(khoa instance);
    partial void Updatekhoa(khoa instance);
    partial void Deletekhoa(khoa instance);
    #endregion
		
		public QLSVDataContext() : 
				base(global::DALL.Properties.Settings.Default.tspConnect, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangViPham> BangViPhams
		{
			get
			{
				return this.GetTable<BangViPham>();
			}
		}
		
		public System.Data.Linq.Table<bangDiem> bangDiems
		{
			get
			{
				return this.GetTable<bangDiem>();
			}
		}
		
		public System.Data.Linq.Table<diemDanh> diemDanhs
		{
			get
			{
				return this.GetTable<diemDanh>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVien> GiaoViens
		{
			get
			{
				return this.GetTable<GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<hocPhan> hocPhans
		{
			get
			{
				return this.GetTable<hocPhan>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<LUUTAIKHOAN> LUUTAIKHOANs
		{
			get
			{
				return this.GetTable<LUUTAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<LOAITAIKHOAN> LOAITAIKHOANs
		{
			get
			{
				return this.GetTable<LOAITAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<khoa> khoas
		{
			get
			{
				return this.GetTable<khoa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangViPham")]
	public partial class BangViPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maVP;
		
		private string _noidungVP;
		
		private string _maSV;
		
		private string _maHP;
		
		private EntityRef<hocPhan> _hocPhan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaVPChanging(string value);
    partial void OnmaVPChanged();
    partial void OnnoidungVPChanging(string value);
    partial void OnnoidungVPChanged();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnmaHPChanging(string value);
    partial void OnmaHPChanged();
    #endregion
		
		public BangViPham()
		{
			this._hocPhan = default(EntityRef<hocPhan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maVP", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maVP
		{
			get
			{
				return this._maVP;
			}
			set
			{
				if ((this._maVP != value))
				{
					this.OnmaVPChanging(value);
					this.SendPropertyChanging();
					this._maVP = value;
					this.SendPropertyChanged("maVP");
					this.OnmaVPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidungVP", DbType="NVarChar(200)")]
		public string noidungVP
		{
			get
			{
				return this._noidungVP;
			}
			set
			{
				if ((this._noidungVP != value))
				{
					this.OnnoidungVPChanging(value);
					this.SendPropertyChanging();
					this._noidungVP = value;
					this.SendPropertyChanged("noidungVP");
					this.OnnoidungVPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHP", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maHP
		{
			get
			{
				return this._maHP;
			}
			set
			{
				if ((this._maHP != value))
				{
					if (this._hocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHPChanging(value);
					this.SendPropertyChanging();
					this._maHP = value;
					this.SendPropertyChanged("maHP");
					this.OnmaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_BangViPham", Storage="_hocPhan", ThisKey="maHP", OtherKey="maHP", IsForeignKey=true)]
		public hocPhan hocPhan
		{
			get
			{
				return this._hocPhan.Entity;
			}
			set
			{
				hocPhan previousValue = this._hocPhan.Entity;
				if (((previousValue != value) 
							|| (this._hocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hocPhan.Entity = null;
						previousValue.BangViPhams.Remove(this);
					}
					this._hocPhan.Entity = value;
					if ((value != null))
					{
						value.BangViPhams.Add(this);
						this._maHP = value.maHP;
					}
					else
					{
						this._maHP = default(string);
					}
					this.SendPropertyChanged("hocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_BangViPham", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.BangViPhams.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.BangViPhams.Add(this);
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bangDiem")]
	public partial class bangDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHP;
		
		private string _maSV;
		
		private string _tenHK;
		
		private System.Nullable<double> _diemGK;
		
		private System.Nullable<double> _diemCK;
		
		private System.Nullable<double> _diemTB;
		
		private System.Nullable<System.DateTime> _thoigian;
		
		private EntityRef<hocPhan> _hocPhan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHPChanging(string value);
    partial void OnmaHPChanged();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OntenHKChanging(string value);
    partial void OntenHKChanged();
    partial void OndiemGKChanging(System.Nullable<double> value);
    partial void OndiemGKChanged();
    partial void OndiemCKChanging(System.Nullable<double> value);
    partial void OndiemCKChanged();
    partial void OndiemTBChanging(System.Nullable<double> value);
    partial void OndiemTBChanged();
    partial void OnthoigianChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigianChanged();
    #endregion
		
		public bangDiem()
		{
			this._hocPhan = default(EntityRef<hocPhan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHP", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maHP
		{
			get
			{
				return this._maHP;
			}
			set
			{
				if ((this._maHP != value))
				{
					if (this._hocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHPChanging(value);
					this.SendPropertyChanging();
					this._maHP = value;
					this.SendPropertyChanged("maHP");
					this.OnmaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHK", DbType="NVarChar(10)")]
		public string tenHK
		{
			get
			{
				return this._tenHK;
			}
			set
			{
				if ((this._tenHK != value))
				{
					this.OntenHKChanging(value);
					this.SendPropertyChanging();
					this._tenHK = value;
					this.SendPropertyChanged("tenHK");
					this.OntenHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemGK", DbType="Float")]
		public System.Nullable<double> diemGK
		{
			get
			{
				return this._diemGK;
			}
			set
			{
				if ((this._diemGK != value))
				{
					this.OndiemGKChanging(value);
					this.SendPropertyChanging();
					this._diemGK = value;
					this.SendPropertyChanged("diemGK");
					this.OndiemGKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemCK", DbType="Float")]
		public System.Nullable<double> diemCK
		{
			get
			{
				return this._diemCK;
			}
			set
			{
				if ((this._diemCK != value))
				{
					this.OndiemCKChanging(value);
					this.SendPropertyChanging();
					this._diemCK = value;
					this.SendPropertyChanged("diemCK");
					this.OndiemCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemTB", DbType="Float")]
		public System.Nullable<double> diemTB
		{
			get
			{
				return this._diemTB;
			}
			set
			{
				if ((this._diemTB != value))
				{
					this.OndiemTBChanging(value);
					this.SendPropertyChanging();
					this._diemTB = value;
					this.SendPropertyChanged("diemTB");
					this.OndiemTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian", DbType="Date")]
		public System.Nullable<System.DateTime> thoigian
		{
			get
			{
				return this._thoigian;
			}
			set
			{
				if ((this._thoigian != value))
				{
					this.OnthoigianChanging(value);
					this.SendPropertyChanging();
					this._thoigian = value;
					this.SendPropertyChanged("thoigian");
					this.OnthoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_bangDiem", Storage="_hocPhan", ThisKey="maHP", OtherKey="maHP", IsForeignKey=true)]
		public hocPhan hocPhan
		{
			get
			{
				return this._hocPhan.Entity;
			}
			set
			{
				hocPhan previousValue = this._hocPhan.Entity;
				if (((previousValue != value) 
							|| (this._hocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hocPhan.Entity = null;
						previousValue.bangDiems.Remove(this);
					}
					this._hocPhan.Entity = value;
					if ((value != null))
					{
						value.bangDiems.Add(this);
						this._maHP = value.maHP;
					}
					else
					{
						this._maHP = default(string);
					}
					this.SendPropertyChanged("hocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_bangDiem", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.bangDiem = null;
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.bangDiem = this;
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.diemDanh")]
	public partial class diemDanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _maHP;
		
		private System.Nullable<int> _sotiet;
		
		private System.DateTime _thoiGian;
		
		private EntityRef<hocPhan> _hocPhan;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnmaHPChanging(string value);
    partial void OnmaHPChanged();
    partial void OnsotietChanging(System.Nullable<int> value);
    partial void OnsotietChanged();
    partial void OnthoiGianChanging(System.DateTime value);
    partial void OnthoiGianChanged();
    #endregion
		
		public diemDanh()
		{
			this._hocPhan = default(EntityRef<hocPhan>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHP", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHP
		{
			get
			{
				return this._maHP;
			}
			set
			{
				if ((this._maHP != value))
				{
					if (this._hocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHPChanging(value);
					this.SendPropertyChanging();
					this._maHP = value;
					this.SendPropertyChanged("maHP");
					this.OnmaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotiet", DbType="Int")]
		public System.Nullable<int> sotiet
		{
			get
			{
				return this._sotiet;
			}
			set
			{
				if ((this._sotiet != value))
				{
					this.OnsotietChanging(value);
					this.SendPropertyChanging();
					this._sotiet = value;
					this.SendPropertyChanged("sotiet");
					this.OnsotietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGian", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime thoiGian
		{
			get
			{
				return this._thoiGian;
			}
			set
			{
				if ((this._thoiGian != value))
				{
					this.OnthoiGianChanging(value);
					this.SendPropertyChanging();
					this._thoiGian = value;
					this.SendPropertyChanged("thoiGian");
					this.OnthoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_diemDanh", Storage="_hocPhan", ThisKey="maHP", OtherKey="maHP", IsForeignKey=true)]
		public hocPhan hocPhan
		{
			get
			{
				return this._hocPhan.Entity;
			}
			set
			{
				hocPhan previousValue = this._hocPhan.Entity;
				if (((previousValue != value) 
							|| (this._hocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hocPhan.Entity = null;
						previousValue.diemDanhs.Remove(this);
					}
					this._hocPhan.Entity = value;
					if ((value != null))
					{
						value.diemDanhs.Add(this);
						this._maHP = value.maHP;
					}
					else
					{
						this._maHP = default(string);
					}
					this.SendPropertyChanged("hocPhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_diemDanh", Storage="_SinhVien", ThisKey="maSV", OtherKey="maSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.diemDanhs.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.diemDanhs.Add(this);
						this._maSV = value.maSV;
					}
					else
					{
						this._maSV = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVien")]
	public partial class GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maGV;
		
		private string _hoTenGV;
		
		private string _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _noiSinh;
		
		private string _sDT;
		
		private string _eMail;
		
		private string _tenCV;
		
		private string _tenLop;
		
		private string _passTK;
		
		private string _maKhoa;
		
		private EntitySet<SinhVien> _SinhViens;
		
		private EntityRef<khoa> _khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGVChanging(string value);
    partial void OnmaGVChanged();
    partial void OnhoTenGVChanging(string value);
    partial void OnhoTenGVChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OnnoiSinhChanging(string value);
    partial void OnnoiSinhChanged();
    partial void OnsDTChanging(string value);
    partial void OnsDTChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OntenCVChanging(string value);
    partial void OntenCVChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnpassTKChanging(string value);
    partial void OnpassTKChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    #endregion
		
		public GiaoVien()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			this._khoa = default(EntityRef<khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenGV", DbType="NVarChar(30)")]
		public string hoTenGV
		{
			get
			{
				return this._hoTenGV;
			}
			set
			{
				if ((this._hoTenGV != value))
				{
					this.OnhoTenGVChanging(value);
					this.SendPropertyChanging();
					this._hoTenGV = value;
					this.SendPropertyChanged("hoTenGV");
					this.OnhoTenGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(40)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(20)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this.OnnoiSinhChanging(value);
					this.SendPropertyChanging();
					this._noiSinh = value;
					this.SendPropertyChanged("noiSinh");
					this.OnnoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDT", DbType="NVarChar(10)")]
		public string sDT
		{
			get
			{
				return this._sDT;
			}
			set
			{
				if ((this._sDT != value))
				{
					this.OnsDTChanging(value);
					this.SendPropertyChanging();
					this._sDT = value;
					this.SendPropertyChanged("sDT");
					this.OnsDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30)")]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCV", DbType="NVarChar(20)")]
		public string tenCV
		{
			get
			{
				return this._tenCV;
			}
			set
			{
				if ((this._tenCV != value))
				{
					this.OntenCVChanging(value);
					this.SendPropertyChanging();
					this._tenCV = value;
					this.SendPropertyChanged("tenCV");
					this.OntenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(20)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passTK", DbType="NVarChar(20)")]
		public string passTK
		{
			get
			{
				return this._passTK;
			}
			set
			{
				if ((this._passTK != value))
				{
					this.OnpassTKChanging(value);
					this.SendPropertyChanging();
					this._passTK = value;
					this.SendPropertyChanged("passTK");
					this.OnpassTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_SinhVien", Storage="_SinhViens", ThisKey="maGV", OtherKey="maGV")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_GiaoVien", Storage="_khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public khoa khoa
		{
			get
			{
				return this._khoa.Entity;
			}
			set
			{
				khoa previousValue = this._khoa.Entity;
				if (((previousValue != value) 
							|| (this._khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khoa.Entity = null;
						previousValue.GiaoViens.Remove(this);
					}
					this._khoa.Entity = value;
					if ((value != null))
					{
						value.GiaoViens.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hocPhan")]
	public partial class hocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHP;
		
		private string _tenHP;
		
		private System.Nullable<int> _soTC;
		
		private string _loaiHP;
		
		private System.Nullable<int> _gia;
		
		private string _tenHK;
		
		private string _maKhoa;
		
		private EntitySet<BangViPham> _BangViPhams;
		
		private EntitySet<bangDiem> _bangDiems;
		
		private EntitySet<diemDanh> _diemDanhs;
		
		private EntityRef<khoa> _khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHPChanging(string value);
    partial void OnmaHPChanged();
    partial void OntenHPChanging(string value);
    partial void OntenHPChanged();
    partial void OnsoTCChanging(System.Nullable<int> value);
    partial void OnsoTCChanged();
    partial void OnloaiHPChanging(string value);
    partial void OnloaiHPChanged();
    partial void OngiaChanging(System.Nullable<int> value);
    partial void OngiaChanged();
    partial void OntenHKChanging(string value);
    partial void OntenHKChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    #endregion
		
		public hocPhan()
		{
			this._BangViPhams = new EntitySet<BangViPham>(new Action<BangViPham>(this.attach_BangViPhams), new Action<BangViPham>(this.detach_BangViPhams));
			this._bangDiems = new EntitySet<bangDiem>(new Action<bangDiem>(this.attach_bangDiems), new Action<bangDiem>(this.detach_bangDiems));
			this._diemDanhs = new EntitySet<diemDanh>(new Action<diemDanh>(this.attach_diemDanhs), new Action<diemDanh>(this.detach_diemDanhs));
			this._khoa = default(EntityRef<khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHP", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHP
		{
			get
			{
				return this._maHP;
			}
			set
			{
				if ((this._maHP != value))
				{
					this.OnmaHPChanging(value);
					this.SendPropertyChanging();
					this._maHP = value;
					this.SendPropertyChanged("maHP");
					this.OnmaHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHP", DbType="NVarChar(30)")]
		public string tenHP
		{
			get
			{
				return this._tenHP;
			}
			set
			{
				if ((this._tenHP != value))
				{
					this.OntenHPChanging(value);
					this.SendPropertyChanging();
					this._tenHP = value;
					this.SendPropertyChanged("tenHP");
					this.OntenHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTC", DbType="Int")]
		public System.Nullable<int> soTC
		{
			get
			{
				return this._soTC;
			}
			set
			{
				if ((this._soTC != value))
				{
					this.OnsoTCChanging(value);
					this.SendPropertyChanging();
					this._soTC = value;
					this.SendPropertyChanged("soTC");
					this.OnsoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHP", DbType="NVarChar(10)")]
		public string loaiHP
		{
			get
			{
				return this._loaiHP;
			}
			set
			{
				if ((this._loaiHP != value))
				{
					this.OnloaiHPChanging(value);
					this.SendPropertyChanging();
					this._loaiHP = value;
					this.SendPropertyChanged("loaiHP");
					this.OnloaiHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Int")]
		public System.Nullable<int> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHK", DbType="NVarChar(10)")]
		public string tenHK
		{
			get
			{
				return this._tenHK;
			}
			set
			{
				if ((this._tenHK != value))
				{
					this.OntenHKChanging(value);
					this.SendPropertyChanging();
					this._tenHK = value;
					this.SendPropertyChanged("tenHK");
					this.OntenHKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NVarChar(20)")]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_BangViPham", Storage="_BangViPhams", ThisKey="maHP", OtherKey="maHP")]
		public EntitySet<BangViPham> BangViPhams
		{
			get
			{
				return this._BangViPhams;
			}
			set
			{
				this._BangViPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_bangDiem", Storage="_bangDiems", ThisKey="maHP", OtherKey="maHP")]
		public EntitySet<bangDiem> bangDiems
		{
			get
			{
				return this._bangDiems;
			}
			set
			{
				this._bangDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hocPhan_diemDanh", Storage="_diemDanhs", ThisKey="maHP", OtherKey="maHP")]
		public EntitySet<diemDanh> diemDanhs
		{
			get
			{
				return this._diemDanhs;
			}
			set
			{
				this._diemDanhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_hocPhan", Storage="_khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public khoa khoa
		{
			get
			{
				return this._khoa.Entity;
			}
			set
			{
				khoa previousValue = this._khoa.Entity;
				if (((previousValue != value) 
							|| (this._khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khoa.Entity = null;
						previousValue.hocPhans.Remove(this);
					}
					this._khoa.Entity = value;
					if ((value != null))
					{
						value.hocPhans.Add(this);
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangViPhams(BangViPham entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = this;
		}
		
		private void detach_BangViPhams(BangViPham entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = null;
		}
		
		private void attach_bangDiems(bangDiem entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = this;
		}
		
		private void detach_bangDiems(bangDiem entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = null;
		}
		
		private void attach_diemDanhs(diemDanh entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = this;
		}
		
		private void detach_diemDanhs(diemDanh entity)
		{
			this.SendPropertyChanging();
			entity.hocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN
	{
		
		private string _TenDangNhap;
		
		private string _HoTen;
		
		private string _MatKhau;
		
		private int _ID;
		
		public TAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this._TenDangNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maSV;
		
		private string _hoTenSV;
		
		private string _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _noiSinh;
		
		private string _sDT;
		
		private string _eMail;
		
		private string _tenCV;
		
		private string _tenLop;
		
		private string _maGV;
		
		private string _passTK;
		
		private EntitySet<BangViPham> _BangViPhams;
		
		private EntityRef<bangDiem> _bangDiem;
		
		private EntitySet<diemDanh> _diemDanhs;
		
		private EntityRef<GiaoVien> _GiaoVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaSVChanging(string value);
    partial void OnmaSVChanged();
    partial void OnhoTenSVChanging(string value);
    partial void OnhoTenSVChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OnnoiSinhChanging(string value);
    partial void OnnoiSinhChanged();
    partial void OnsDTChanging(string value);
    partial void OnsDTChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OntenCVChanging(string value);
    partial void OntenCVChanged();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnmaGVChanging(string value);
    partial void OnmaGVChanged();
    partial void OnpassTKChanging(string value);
    partial void OnpassTKChanged();
    #endregion
		
		public SinhVien()
		{
			this._BangViPhams = new EntitySet<BangViPham>(new Action<BangViPham>(this.attach_BangViPhams), new Action<BangViPham>(this.detach_BangViPhams));
			this._bangDiem = default(EntityRef<bangDiem>);
			this._diemDanhs = new EntitySet<diemDanh>(new Action<diemDanh>(this.attach_diemDanhs), new Action<diemDanh>(this.detach_diemDanhs));
			this._GiaoVien = default(EntityRef<GiaoVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maSV", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maSV
		{
			get
			{
				return this._maSV;
			}
			set
			{
				if ((this._maSV != value))
				{
					this.OnmaSVChanging(value);
					this.SendPropertyChanging();
					this._maSV = value;
					this.SendPropertyChanged("maSV");
					this.OnmaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenSV", DbType="NVarChar(30)")]
		public string hoTenSV
		{
			get
			{
				return this._hoTenSV;
			}
			set
			{
				if ((this._hoTenSV != value))
				{
					this.OnhoTenSVChanging(value);
					this.SendPropertyChanging();
					this._hoTenSV = value;
					this.SendPropertyChanged("hoTenSV");
					this.OnhoTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(40)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiSinh", DbType="NVarChar(20)")]
		public string noiSinh
		{
			get
			{
				return this._noiSinh;
			}
			set
			{
				if ((this._noiSinh != value))
				{
					this.OnnoiSinhChanging(value);
					this.SendPropertyChanging();
					this._noiSinh = value;
					this.SendPropertyChanged("noiSinh");
					this.OnnoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDT", DbType="NVarChar(10)")]
		public string sDT
		{
			get
			{
				return this._sDT;
			}
			set
			{
				if ((this._sDT != value))
				{
					this.OnsDTChanging(value);
					this.SendPropertyChanging();
					this._sDT = value;
					this.SendPropertyChanged("sDT");
					this.OnsDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30)")]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCV", DbType="NVarChar(20)")]
		public string tenCV
		{
			get
			{
				return this._tenCV;
			}
			set
			{
				if ((this._tenCV != value))
				{
					this.OntenCVChanging(value);
					this.SendPropertyChanging();
					this._tenCV = value;
					this.SendPropertyChanged("tenCV");
					this.OntenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(20)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGV", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maGV
		{
			get
			{
				return this._maGV;
			}
			set
			{
				if ((this._maGV != value))
				{
					if (this._GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaGVChanging(value);
					this.SendPropertyChanging();
					this._maGV = value;
					this.SendPropertyChanged("maGV");
					this.OnmaGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passTK", DbType="NVarChar(20)")]
		public string passTK
		{
			get
			{
				return this._passTK;
			}
			set
			{
				if ((this._passTK != value))
				{
					this.OnpassTKChanging(value);
					this.SendPropertyChanging();
					this._passTK = value;
					this.SendPropertyChanged("passTK");
					this.OnpassTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_BangViPham", Storage="_BangViPhams", ThisKey="maSV", OtherKey="maSV")]
		public EntitySet<BangViPham> BangViPhams
		{
			get
			{
				return this._BangViPhams;
			}
			set
			{
				this._BangViPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_bangDiem", Storage="_bangDiem", ThisKey="maSV", OtherKey="maSV", IsUnique=true, IsForeignKey=false)]
		public bangDiem bangDiem
		{
			get
			{
				return this._bangDiem.Entity;
			}
			set
			{
				bangDiem previousValue = this._bangDiem.Entity;
				if (((previousValue != value) 
							|| (this._bangDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bangDiem.Entity = null;
						previousValue.SinhVien = null;
					}
					this._bangDiem.Entity = value;
					if ((value != null))
					{
						value.SinhVien = this;
					}
					this.SendPropertyChanged("bangDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_diemDanh", Storage="_diemDanhs", ThisKey="maSV", OtherKey="maSV")]
		public EntitySet<diemDanh> diemDanhs
		{
			get
			{
				return this._diemDanhs;
			}
			set
			{
				this._diemDanhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVien_SinhVien", Storage="_GiaoVien", ThisKey="maGV", OtherKey="maGV", IsForeignKey=true)]
		public GiaoVien GiaoVien
		{
			get
			{
				return this._GiaoVien.Entity;
			}
			set
			{
				GiaoVien previousValue = this._GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVien.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._GiaoVien.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._maGV = value.maGV;
					}
					else
					{
						this._maGV = default(string);
					}
					this.SendPropertyChanged("GiaoVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangViPhams(BangViPham entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_BangViPhams(BangViPham entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
		
		private void attach_diemDanhs(diemDanh entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_diemDanhs(diemDanh entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUUTAIKHOAN")]
	public partial class LUUTAIKHOAN
	{
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		public LUUTAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this._TenDangNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITAIKHOAN")]
	public partial class LOAITAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LOAITAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenLop;
		
		private string _maKhoa;
		
		private EntityRef<khoa> _khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenLopChanging(string value);
    partial void OntenLopChanged();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    #endregion
		
		public Lop()
		{
			this._khoa = default(EntityRef<khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLop", DbType="NVarChar(20)")]
		public string tenLop
		{
			get
			{
				return this._tenLop;
			}
			set
			{
				if ((this._tenLop != value))
				{
					this.OntenLopChanging(value);
					this.SendPropertyChanging();
					this._tenLop = value;
					this.SendPropertyChanged("tenLop");
					this.OntenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					if (this._khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_Lop", Storage="_khoa", ThisKey="maKhoa", OtherKey="maKhoa", IsForeignKey=true)]
		public khoa khoa
		{
			get
			{
				return this._khoa.Entity;
			}
			set
			{
				khoa previousValue = this._khoa.Entity;
				if (((previousValue != value) 
							|| (this._khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khoa.Entity = null;
						previousValue.Lop = null;
					}
					this._khoa.Entity = value;
					if ((value != null))
					{
						value.Lop = this;
						this._maKhoa = value.maKhoa;
					}
					else
					{
						this._maKhoa = default(string);
					}
					this.SendPropertyChanged("khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khoa")]
	public partial class khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhoa;
		
		private string _tenKhoa;
		
		private EntitySet<GiaoVien> _GiaoViens;
		
		private EntitySet<hocPhan> _hocPhans;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoaChanging(string value);
    partial void OnmaKhoaChanged();
    partial void OntenKhoaChanging(string value);
    partial void OntenKhoaChanged();
    #endregion
		
		public khoa()
		{
			this._GiaoViens = new EntitySet<GiaoVien>(new Action<GiaoVien>(this.attach_GiaoViens), new Action<GiaoVien>(this.detach_GiaoViens));
			this._hocPhans = new EntitySet<hocPhan>(new Action<hocPhan>(this.attach_hocPhans), new Action<hocPhan>(this.detach_hocPhans));
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoa", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoa
		{
			get
			{
				return this._maKhoa;
			}
			set
			{
				if ((this._maKhoa != value))
				{
					this.OnmaKhoaChanging(value);
					this.SendPropertyChanging();
					this._maKhoa = value;
					this.SendPropertyChanged("maKhoa");
					this.OnmaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoa", DbType="NVarChar(30)")]
		public string tenKhoa
		{
			get
			{
				return this._tenKhoa;
			}
			set
			{
				if ((this._tenKhoa != value))
				{
					this.OntenKhoaChanging(value);
					this.SendPropertyChanging();
					this._tenKhoa = value;
					this.SendPropertyChanged("tenKhoa");
					this.OntenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_GiaoVien", Storage="_GiaoViens", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<GiaoVien> GiaoViens
		{
			get
			{
				return this._GiaoViens;
			}
			set
			{
				this._GiaoViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_hocPhan", Storage="_hocPhans", ThisKey="maKhoa", OtherKey="maKhoa")]
		public EntitySet<hocPhan> hocPhans
		{
			get
			{
				return this._hocPhans;
			}
			set
			{
				this._hocPhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_Lop", Storage="_Lop", ThisKey="maKhoa", OtherKey="maKhoa", IsUnique=true, IsForeignKey=false)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.khoa = null;
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.khoa = this;
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.khoa = this;
		}
		
		private void detach_GiaoViens(GiaoVien entity)
		{
			this.SendPropertyChanging();
			entity.khoa = null;
		}
		
		private void attach_hocPhans(hocPhan entity)
		{
			this.SendPropertyChanging();
			entity.khoa = this;
		}
		
		private void detach_hocPhans(hocPhan entity)
		{
			this.SendPropertyChanging();
			entity.khoa = null;
		}
	}
}
#pragma warning restore 1591
